Lunattic/config/routes.rb
Rails.application.routes.draw do
  #get 'pages#home'
  #get 'devise/sessions#new'
  get "create", to: "produtos#new"
  

  root to: "produtos#index"
  devise_for :users
  resources :produtos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Lunattic/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Lunattic/app/models/produto.rb
class Produto < ApplicationRecord
	#Ian eu sei que era para por isso, mas essa porra buga o programa todo *-*
	belongs_to: user
end

Lunattic/app/models/user.rb
class User < ApplicationRecord
  #Ian eu sei que era para por isso, mas essa porra buga o programa todo belongs_to: produto  *-*  has_many: produto
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

Lunattic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Lunattic/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

Lunattic/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:titulo, :conteudo, :preco, :url, :estoque)
    end
end

Lunattic/app/helpers/application_helper.rb
module ApplicationHelper
end

Lunattic/app/helpers/pages_helper.rb
module PagesHelper
end

Lunattic/app/helpers/produtos_helper.rb
module ProdutosHelper
end

Lunattic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunattic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Lunattic/app/views/pages/home.html.erb
<h1> Lunattic </h1> 
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%if current_user %>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

<% link_to 'Sign up', new_user_registration_path %>

<% link_to 'Sign in', new_user_session_path %>
<% end %>

Lunattic/app/views/produtos/_form.html.erb
<h1> Lunattic </h1> 
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :estoque %>
    <%= form.check_box :estoque %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Lunattic/app/views/produtos/edit.html.erb
<h1> Lunattic </h1> 
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

Lunattic/app/views/produtos/index.html.erb
<h1> Lunattic </h1> 
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th>Preco</th>
      <th>Url</th>
      <!-- A  ideia era colocar  <PORCENTO= image_tag @produto.url.url('300x300') PORCENTO>, mas não consigo adaptar o url ao img src=""   -->
      <!--< image_tag @produto.url.url('300x300') > -->
      <th>Estoque</th>
      <th colspan="3"></th>
    </tr>
  </thead>


<!-- Client.where("orders_count = '2'") -->

  <tbody>
    <% @produtos.each do |produto| %>   <!-- Isso irá fazer todos os produtos criados serem carregados.  -->
    <% if produto.estoque  == true  %>  <!-- Se o atributo estoque for verdadeiro mostre o item. -->
      <tr>
        <td><%= produto.titulo %></td>
        <td><%= produto.conteudo %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.url %></td>
        <td><img src="<%= produto.url %>"></td>  <!-- O que vai ocorrer aqui é oa tributo URL ocupando o texto da src da img. -->
        <!--   NAO CONSEGUI ASSIM TMB <td><PORCENTO= image_tag produto.url('300x300') PORCENTO> </td>   -->
        <!-- Ian, eu consegui, sou p1k4 :D -->
        <td><%= produto.estoque %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
       <% end %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

Lunattic/app/views/produtos/new.html.erb
<h1> Lunattic </h1> 
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

Lunattic/app/views/produtos/show.html.erb
<h1> Lunattic </h1> 
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @produto.titulo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @produto.conteudo %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Url:</strong>
  <%= @produto.url %>
</p>

<p>
  <strong>Estoque:</strong>
  <%= @produto.estoque %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>